version: '3'

services:

  postgres:
    image: 'postgres:9.5'
    environment:
      - POSTGRES_USER=numbers
      - POSTGRES_PASSWORD=plusminus
      - POSTGRES_DB=numbers
    ports:
      - '5432:5432'
    deploy:
      replicas: 1
    networks:
      - default
    volumes:
      - 'data:/var/lib/postgresql/data'

  website:
    image: 'stabenfeldt/mesh-numbers:latest'
    environment:
      - OFFICE_RND_TOKEN=${OFFICE_RND_TOKEN}
    depends_on:
      - 'postgres'
    ports:
      - '3000:3000'
    volumes:
      - 'data:/numbers'
    env_file:
      - '.env'
    stdin_open: true
    tty: true
    networks:
      - default
      - proxy
    deploy:
      replicas: 1



volumes:
  data:

networks:
  default:
    external: false
  proxy:
    external: true
