version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      - POSTGRES_USER=numbers
      - POSTGRES_PASSWORD=plusminus
      - POSTGRES_DB=numbers
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  website:
    build: .
    environment:
      - OFFICE_RND_TOKEN
    depends_on:
      - 'postgres'
    ports:
      - '3000:3000'
    volumes:
      - '.:/numbers'
    env_file:
      - '.env'
    stdin_open: true
    tty: true



volumes:
  postgres:
