version: 2
jobs:
  build:
    working_directory: /numbers
    docker:
      - image: stabenfeldt/ubuntu-w-docker-compose:1
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose run website rspec -f d

      - deploy:
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag numbers_website $DOCKER_HUB_USER_ID/$PROJECT_NAME:$CIRCLE_SHA1
            docker tag numbers_website $DOCKER_HUB_USER_ID/$PROJECT_NAME:latest
            docker push $DOCKER_HUB_USER_ID/$PROJECT_NAME:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/$PROJECT_NAME:latest
